### ISSUE TITLE
Re-factorize everything drawn to a uniform interface

### ISSUE THREAD

**Issue by ShaggO** [Munksgaard/gamemenu#7]
It would be beneficial to have a common interface for every "component" that needs to be drawn on the screen. This way we can simply maintain a list of objects to be drawn at every timestep and ease the implementation of a generic precipitation.

**Comment by ShaggO** [comment]
We need to decide whether the screen should be part of the IScreenObject so we don't need to pass it to every update and draw function call.

**Comment by Munksgaard** [comment]
I think that's a good idea.
